version: '3.7'

services:
  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app/
    ports:
      - 1337:8000
    depends_on:
      - redis

  celery:
    build: ./project
    command: celery worker --app=core --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./project:/usr/src/app
    depends_on:
      - web
      - redis

  dashboard:
    build: ./project
    command: flower -A core --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    depends_on:
      - web
      - redis
      - celery

  redis:
    image: redis:5-alpine
