# Generated by Django 3.1.2 on 2020-10-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201030_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.CharField(max_length=63, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.CharField(max_length=31, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='slug',
            field=models.CharField(max_length=63, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.CharField(max_length=63, unique=True, verbose_name='Слаг'),
        ),
    ]
