# Generated by Django 3.1.2 on 2020-10-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201030_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='api.Task', verbose_name='Задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='api.Language', verbose_name='Языки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='api.Group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='api.Task', verbose_name='Задачи'),
        ),
    ]
