# Generated by Django 3.0.4 on 2020-10-31 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201031_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='path',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tests',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_directory_path',
        ),
    ]
