# Generated by Django 3.1.2 on 2020-10-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201031_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcheck',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время сдачи'),
        ),
    ]
