# Generated by Django 3.1.2 on 2020-10-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201031_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='groups', to='api.User', verbose_name='Пользователи'),
        ),
    ]
