# Generated by Django 3.1.2 on 2020-10-31 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201031_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.layout', verbose_name='Шаблон'),
        ),
    ]
