FROM cmplopes/alpine-freepascal:latest

ADD entrypoint.sh /entrypoint.sh

CMD ["/entrypoint.sh"]

# docker run \
# -it --rm \
# -v "$PWD/source:/source" \
# -v "$PWD/tests:/tests" \
# dimastark/pascal-runner
