# Generated by Django 3.1.2 on 2020-10-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=127, verbose_name='E-mail')),
                ('login', models.CharField(max_length=127, verbose_name='Логин')),
                ('password', models.CharField(max_length=127, verbose_name='Пароль')),
                ('middle_name', models.CharField(max_length=127, verbose_name='Отчество')),
                ('first_name', models.CharField(max_length=127, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=127, verbose_name='Фамилия')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('user_type', models.CharField(choices=[('teacher', 'Учитель'), ('student', 'Студент')], max_length=31, verbose_name='Роль')),
            ],
        ),
    ]
